### ISSUE TITLE
Inventario

### ISSUE THREAD

**Issue by juanseguravasco** [Sede-Galicia/proyecto-integrador#1]
Tenéis que decirme cuántos adaptadores tenéis ahora:
- de USB a RJ45
- de vídeom (VGA a HDMI, Display porrt, VDI, ...)

También falta inventariar el switch CIsco, ¿o es que no tenéis?
Y las fuentes de alimentación, para ver si tenéis para todo (Mikrotic, router TP-Link y switch TP-Link)

**Comment by asenabre03** [comment]
- Todavía faltan los adaptadores **RJ45 to USB** porque todavía no sabemos cuantos usaremos, aun debemos pensar en los servidores que tendremos y en cuantas tarjetas de red tendremos.

- Tenemos **1** adaptador **VGA to HDMI** que ya estaba documentado.

- El **Switch CISCO** al estar anclado y no poder sacarlo lo pase por encima y no lo puse en el inventario, ya esta puesto.

- Nos faltan los alimentadores del **MikroTik** y del Switch **TP-LINK con 8 bocas Ethernet**, solamente tenemos el alimentador del **Router TP-LINK**.

> Estaremos esperando los alimentadores para poder usar dicho hardware cuando antes sea posible y cuando sepamos cuantas tarjetas de red usaremos, lo indicaremos en [inventario.md](https://github.com/Sede-Galicia/proyecto-integrador/blob/main/inventario/inventario.md)

**Comment by asenabre03** [comment]
- Todavía faltan los adaptadores **RJ45 to USB** porque todavía no sabemos cuantos usaremos, aun debemos pensar en los servidores que tendremos y en cuantas tarjetas de red tendremos.

- Tenemos **1** adaptador **VGA to HDMI** que ya estaba documentado.

- El **Switch CISCO** al estar anclado y no poder sacarlo lo pase por encima y no lo puse en el inventario, ya esta puesto.

- Nos faltan los alimentadores del **MikroTik** y del Switch **TP-LINK con 8 bocas Ethernet**, solamente tenemos el alimentador del **Router TP-LINK**.

> Estaremos esperando los alimentadores para poder usar dicho hardware cuanto antes sea posible.

**Comment by asenabre03** [comment]
> Cierro esto, ya esta todo OK.
